package com.event.sourcing.order.event;

public enum OrderStatus {
	CART_INITIATED, CART_CREATED, CART_ITEM_ADDED, CART_ITEM_REMOVED, CART_REMOVED, 
	ORDER_INITIATED, ORDER_CREATED, ORDER_DELIVERED, ORDER_CANCELLED, ORDER_FAILURE;
}
